# This file was generated by GoReleaser. DO NOT EDIT.
class SyncDotenv < Formula
  desc "sync-dotenv helps you to keep your .env.example in sync with your .env file."
  homepage "https://github.com/atrox/sync-dotenv"
  url "https://github.com/Atrox/sync-dotenv/releases/download/v0.1.2/sync-dotenv_0.1.2_Darwin_x86_64.tar.gz"
  version "0.1.2"
  sha256 "4d0c945958f8be1d540fb92093d354051e1feb1cfb173cac5ceef8accce13492"

  def install
    bin.install "sync-dotenv"
  end

  test do
    system "#{bin}/sync-dotenv --version"
  end
end
