# This file was generated by GoReleaser. DO NOT EDIT.
class SyncDotenv < Formula
  desc "sync-dotenv helps you to keep your .env.example in sync with your .env file."
  homepage "https://atrox.dev"
  url "https://github.com/Atrox/sync-dotenv/releases/download/v0.1.0/sync-dotenv_0.1.0_Darwin_x86_64.tar.gz"
  version "0.1.0"
  sha256 "fe61e83811633138b44dbd88116463d01605444783440e2747719b002004a903"

  def install
    bin.install "sync-dotenv"
  end
end
